### PR TITLE
bootstrap test

### PR DESCRIPTION
**Pull request by rzaluska**
testowy PR

### CODE REVIEW

**Comment by LuXuryPro** [comment]
test this please

**Comment by LuXuryPro** [comment]
test this please

**Comment by LuXuryPro** [comment]
test this please

**Comment by LuXuryPro** [comment]
test this please

**Comment by LuXuryPro** [comment]
test this please

**Comment by LuXuryPro** [comment]
test this please

**Comment by rzaluska** [comment]
test this please

**Pull request closed without merging**
